name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_scripts: ${{ steps.changes.outputs.changed_scripts }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Filter changed scripts
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            changed:
              - '**/*.sh'

      - name: Extract changed files
        id: changes
        env:
          changed: ${{ steps.filter.outputs.changed_files }}
        run: |
          echo "shell: $0"
          echo "# Changed Files" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          changed_scripts="$( echo $changed | jq -r '.[]' | jq -s -R -c 'split("\n") | map(select(. != ""))' )"
          echo "${changed_scripts}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "changed_scripts=${changed_scripts}" >> $GITHUB_OUTPUT

  lint-and-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_scripts != '[]'
    strategy:
      matrix:
        changed_script: ${{ fromJSON(needs.detect-changes.outputs.changed_scripts) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      #- name: Build Docker image
      #  run: docker build -t rhel8:latest .

      - name: Install ShellCheck and ShellSpec
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck git curl kcov
          curl -fsSL https://git.io/shellspec | sh -s -- --yes && ln -s /root/.local/lib/shellspec/shellspec /usr/local/bin/

      - name: Run ShellCheck
        if: ${{ !contains(matrix.changed_script, '_spec') }}
        run: |
          echo "shell: $0"
          echo "# ShellCheck Result" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          shellcheck --format=gcc --severity=error ${{ matrix.changed_script }} >> $GITHUB_STEP_SUMMARY
          shellcheck --format=gcc --severity=error ${{ matrix.changed_script }} | grep 'error' && exit 1
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Run ShellSpec
        run: |
          echo "shell: $0"
          echo "# ShellSpec Result" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          SCRIPT_DIR=$(echo ${{ matrix.changed_script }} | cut -d'/' -f1)
          SCRIPT_FILE=$(basename ${{ matrix.changed_script }} | sed "s/_spec//g")
          cd $SCRIPT_DIR
          shellspec --init >> $GITHUB_STEP_SUMMARY
          chmod +x $SCRIPT_FILE >> $GITHUB_STEP_SUMMARY
          shellspec -s bash --kcov >> $GITHUB_STEP_SUMMARY
          COVERAGE=$(shellspec -s bash --kcov | grep 'Code covered' | sed 's/.*covered: \([0-9]*\)\.[0-9]*%.*/\1/g')
          if (( $COVERAGE < 70 )); then exit 1; fi
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
