name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_scripts: ${{ steps.filter.outputs.changed_scripts }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Filter changed scripts
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            changed:
              - '*_script*/**'

      - name: Extract changed files
        id: changes
        run: |
          changed_scripts=$(echo "${{ steps.filter.outputs.changed_files }}" | jq -r '.[]')
          echo "changed_scripts=${changed_scripts}" >> $GITHUB_OUTPUT

  lint-and-test:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.changed_scripts != '[]'
    strategy:
      matrix:
        changed_script: ${{ fromJSON(needs.detect-changes.outputs.changed_scripts) }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: echo target
        run: |
          echo ${{ matrix.changed_script }} 