name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_scripts: ${{ steps.changes.outputs.changed_scripts }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Filter changed scripts
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            changed:
              - '*_script*/*.sh'

      - name: Extract changed files
        id: changes
        env:
          changed: ${{ steps.filter.outputs.changed_files }}
        run: |
          changed_scripts="$( echo $changed | jq -r '.[]' | jq -s -R -c 'split("\n") | map(select(. != ""))' )"
          echo "changed_scripts=${changed_scripts}" >> $GITHUB_OUTPUT

  lint-and-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_scripts != '[]'
    strategy:
      matrix:
        changed_script: ${{ fromJSON(needs.detect-changes.outputs.changed_scripts) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      #- name: Build Docker image
      #  run: docker build -t rhel8:latest .

      - name: Install ShellCheck and ShellSpec
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck git curl
          curl -fsSL https://git.io/shellspec | sh -s -- --yes && ln -s /root/.local/lib/shellspec/shellspec /usr/local/bin/

      - name: Run ShellCheck
        if: ${{ !contains(matrix.script_path, '_spec') }}
        run: |
          shellcheck --format=gcc --severity=error ${{ matrix.script_path }}
          shellcheck --format=gcc --severity=error ${{ matrix.script_path }} | grep 'error' && exit 1
